/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'MarkPerry' at '8/10/13 2:13 PM' with Gradle 1.8
 *
 * @author MarkPerry, @date 8/10/13 2:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
